fail_fast: false
repos:
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: clang-format
        args: [--style=LLVM]
      - id: clang-tidy
        args: [-p $HOME/atos_ws/build/, -export-fixes /tmp/clang-tidy-result/fixes.yaml, --checks=cppcoreguidelines-*,clang-analyzer-*]
      - id: cppcheck