version: "3.2"
services:
  atos:
    image: astazero/atos_docker_env:latest
    build: 
      context: .
      dockerfile: ./Dockerfile
    network_mode: host
    ipc: host
    stop_signal: SIGINT
    privileged: true
    stdin_open: true
    tty: true
    volumes:
      - ~/.astazero/ATOS/:/root/.astazero/ATOS/
    command: bash -c "source /root/atos_ws/install/setup.sh ; ros2 launch atos launch_basic.py"
