atos:
  mqtt_bridge:
    ros__parameters:
      broker_ip: ""
      pub_client_id: "ATOS"
      username: ""
      password: ""
      topic: ""
      quality_of_service: "1"
  atos_base:
    ros__parameters:
      test_origin_latitude: 57.777073115
      test_origin_longitude: 12.781295498333
      test_origin_altitude: 193.114
      test_origin_rot_x: 0.0
      test_origin_rot_y: 0.0
      test_origin_rot_z: 0.0
      test_origin_rot_w: 1.0
  esmini_adapter:
    ros__parameters:
      open_scenario_file: "DroneScenario.xosc"
  object_control:
    ros__parameters:
      max_missing_heartbeats: 100
      transmitter_id: 15
  system_control:
    ros__parameters:
      gui_update_rate: 20
      