[build-system]
requires = ["flit_core >=3.2,<4","myst_parser >= 1.0.0"]
build-backend = "flit_core.buildapi"

[project]
name = "ATOS"
authors = [{name = "NightShift", email = "asta@zero.com"}]
dynamic = ["version", "description"]