name: Docker Image CI

on:
  push:
    branches: [ "dev" ]

jobs:
  build_dockerImage:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@v3
      with:
        submodules: recursive
        
    # BuildX allows creation of a managed and customizable BuildKit environment
    # in a dedicated Docker container
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag atos:$(date +%s)
